spring.application.name=endgame-api

# --- CONFIGURATION MYSQL ---
# Remplace 'endgame_db' par le nom de ta base créée dans MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/endgame_db
spring.datasource.username=endgame_user
spring.datasource.password=password

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- API RAWG ---
rawg.api.key={}
rawg.api.url=https://api.rawg.io/api

server.address=0.0.0.0